name: portfolio
description: "A responsive personal portfolio website built with Flutter."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1
  scroll_to_index: ^3.0.1
  responsive_framework: ^1.4.0
  hover: ^0.4.2
  flutter_staggered_animations: ^1.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/profile.svg
    - assets/images/project1.svg
    - assets/images/project2.svg
    - assets/images/project3.svg
    - assets/icons/
    - assets/icons/github.svg
    - assets/icons/linkedin.svg
    - assets/icons/twitter.svg
    - assets/icons/email.svg
    - assets/icons/phone.svg
    - assets/icons/location.svg

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
