// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZZBe9lqShMYj7ixaaUeEtcM56VvFVOxY',
    appId: '1:13377596915:web:93c6cf2c0c5ef7fc18f686',
    messagingSenderId: '13377596915',
    projectId: 'myportfolio-2eae0',
    authDomain: 'myportfolio-2eae0.firebaseapp.com',
    storageBucket: 'myportfolio-2eae0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZZBe9lqShMYj7ixaaUeEtcM56VvFVOxY',
    appId: '1:13377596915:android:93c6cf2c0c5ef7fc18f686',
    messagingSenderId: '13377596915',
    projectId: 'myportfolio-2eae0',
    storageBucket: 'myportfolio-2eae0.firebasestorage.app',
    // SHA-1: D7:D3:98:BC:0A:E0:26:6D:CD:AB:67:68:6F:61:C5:9A:A6:3D:65:F3
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZBe9lqShMYj7ixaaUeEtcM56VvFVOxY',
    appId: '1:13377596915:ios:93c6cf2c0c5ef7fc18f686',
    messagingSenderId: '13377596915',
    projectId: 'myportfolio-2eae0',
    storageBucket: 'myportfolio-2eae0.firebasestorage.app',
    iosClientId: '13377596915-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.mohit.career.portfolio',
  );
} 